[package]
name = "api"
version = "0.1.0"
authors = ["Danilo Pereira <dnp1@users.noreply.github.com>"]

#[dependencies.iron]
#    git = "https://github.com/iron/iron.git"
[dependencies]
iron="0.5.1"
persistent="*"
router = "*"
mount = "*"
staticfile="*"
postgres = "*"
r2d2="*"
r2d2_postgres="*"
handlebars-iron="*"
rustc-serialize = "*"
frank_jwt = "2.5.1"
serde = "1.0.19"
serde_json= "*"
serde_derive="*"

[dependencies.params]
git = "https://github.com/iron/params.git"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"